
name: check all fields
on:
  workflow_dispatch:
jobs:
  check-exodus:
    runs-on: ubuntu-latest
    steps:
      - name: Run the action
        id: export
        uses: potatoqualitee/exodus@v1.1
        with:
          specific-twitter-accounts: PSConfEU, DataGrillen
          account-followers: DataGrillen
          accounts-following: DataGrillen, SQLBits
          list-members: "1491474973998915587, 1569973251161616385"
          list-followers: "1569973251161616385"
          hashtags: "#sqlfamily, pbifamily"
          include-private: false
          my: all
          my-specific-list-names: Birdie Favorites
          my-specific-list-keywords: Birdie
          mastodon-csv-filepath: ma.csv
          twitter-csv-filepath: tw.csv
        env:
          BLUEBIRDPS_API_KEY: "${{ secrets.BLUEBIRDPS_API_KEY }}"
          BLUEBIRDPS_API_SECRET: "${{ secrets.BLUEBIRDPS_API_SECRET }}"
          BLUEBIRDPS_ACCESS_TOKEN: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN }}"
          BLUEBIRDPS_ACCESS_TOKEN_SECRET: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN_SECRET }}"
          BLUEBIRDPS_BEARER_TOKEN: "${{ secrets.BLUEBIRDPS_BEARER_TOKEN }}"
