name: Test Community
on:
  push:
  workflow_dispatch:
jobs:
  check-sql:
    runs-on: ubuntu-latest
    steps:
    - name: Run the action
      id: export
      uses: potatoqualitee/exodus@v1.1
      with:
        communities: databash_live, DataTgif
        accounts-following: |
          cl
          psdbatools
      env:
        BLUEBIRDPS_API_KEY: "${{ secrets.BLUEBIRDPS_API_KEY }}"
        BLUEBIRDPS_API_SECRET: "${{ secrets.BLUEBIRDPS_API_SECRET }}"
        BLUEBIRDPS_ACCESS_TOKEN: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN }}"
        BLUEBIRDPS_ACCESS_TOKEN_SECRET: "${{ secrets.BLUEBIRDPS_ACCESS_TOKEN_SECRET }}"
        BLUEBIRDPS_BEARER_TOKEN: "${{ secrets.BLUEBIRDPS_BEARER_TOKEN }}"